spring.datasource.url=jdbc:jtds:sqlserver://tigo.makiro.com.bo/BDSistemaAntenaPM
spring.datasource.username=sistemas
spring.datasource.password=sametsis
spring.datasource.driver-class-name=net.sourceforge.jtds.jdbc.Driver

# Parametros extra para conexiones dinamicas por sucursal
app.datasource.params=
auth.login.validar-sucursal=false
auth.jwt.enabled=true
auth.jwt.access-ttl-minutes=480
auth.jwt.secret=CHANGE_ME_SUPER_SECRET_KEY_2026_TIGOSTAR_SYSTEM_32B
app.cors.allowed-origins=http://localhost:5173,http://127.0.0.1:5173,https://*.ngrok-free.app,https://*.ngrok-free.dev

# jTDS no soporta isValid(); Hikari requiere query de validación.
spring.datasource.hikari.connection-test-query=SELECT 1
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Conexion BD central (Conformacion Cuadrilla Confirmada)
app.central.datasource.url=jdbc:jtds:sqlserver://172.16.0.13/BDControlOrdenes
app.central.datasource.username=${spring.datasource.username}
app.central.datasource.password=${spring.datasource.password}
app.central.datasource.driver-class-name=${spring.datasource.driver-class-name}
app.central.datasource.hikari.connection-test-query=SELECT 1

# Conexion BD TigoHogar (Llamada de Atencion)
app.tigohogar.datasource.url=jdbc:jtds:sqlserver://181.188.148.59/BD_TigoHogar
app.tigohogar.datasource.username=lolivares
app.tigohogar.datasource.password=S3rtelSRL2012
app.tigohogar.datasource.driver-class-name=${spring.datasource.driver-class-name}
app.tigohogar.datasource.hikari.connection-test-query=SELECT 1

# Carpeta local por servidor para imagenes de firmas llamada de atencion
app.llamada-atencion.firmas.dir=C:/imagenes_cuadrillas

# Notificacion por correo de cuadrillas no confirmadas
spring.mail.host=vps-1537170-x.dattaweb.com
spring.mail.port=587
spring.mail.username=sistemas_sc@makiro.com.bo
spring.mail.password=M@kiro15
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.protocols=TLSv1.2
app.cuadrilla.mail.enabled=true
app.cuadrilla.mail.to=cabrerajosue715@gmail.com
app.cuadrilla.mail.from=sistemas_sc@makiro.com.bo
